import { NextRequest, NextResponse } from 'next/server';
import * as cheerio from 'cheerio';

export async function POST(request: NextRequest) {
  try {
    const { url } = await request.json();

    if (!url) {
      return NextResponse.json({ error: 'URL is required' }, { status: 400 });
    }

    // Step 1: Scrape the webpage content
    console.log('Scraping URL for batch processing:', url);
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch URL: ${response.status} ${response.statusText}`);
    }

    const html = await response.text();
    
    // Step 2: Extract content using Cheerio
    const $ = cheerio.load(html);
    
    // Remove script and style elements
    $('script, style, nav, header, footer, aside, .nav, .navigation, .menu, .sidebar').remove();
    
    // Extract text content from main content areas
    let content = '';
    const contentSelectors = [
      'main',
      '[role="main"]',
      '.main',
      '.content',
      '.post',
      '.article',
      '.press-release',
      '.news',
      'article',
      '.entry-content',
      '.post-content'
    ];
    
    // Try to find main content using common selectors
    for (const selector of contentSelectors) {
      const element = $(selector);
      if (element.length > 0) {
        content = element.text().trim();
        break;
      }
    }
    
    // If no main content found, use body but filter out common noise
    if (!content) {
      content = $('body').text().trim();
    }
    
    // Clean up the content
    content = content
      .replace(/\s+/g, ' ')
      .replace(/\n\s*\n/g, '\n')
      .trim();
    
    if (!content || content.length < 100) {
      return NextResponse.json({ error: 'No meaningful content found on the page' }, { status: 400 });
    }

    console.log('Extracted content length:', content.length);

    // Step 3: Generate summary using non-streaming OpenRouter API
    try {
      // Prepare the prompt for professional analyst summary
      const prompt = `You are a professional business analyst. Please analyze the following press release content and provide a comprehensive, well-structured summary. 

Format your response as follows:
- **Executive Summary**: A brief overview in 2-3 sentences
- **Key Announcements**: Main points and announcements
- **Financial Highlights**: Any financial data, revenue, profits, etc.
- **Strategic Implications**: Business impact and strategic importance
- **Key Figures**: Important people mentioned
- **Timeline**: Important dates mentioned
- **Market Impact**: Potential effects on market/industry

Keep the analysis professional, objective, and well-formatted with clear headings and bullet points where appropriate.

Content to analyze:
${content}`;

      const openRouterResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'google/gemini-2.5-flash-lite',
          messages: [{ role: 'user', content: prompt }],
          // No stream property - defaults to false for standard completion
        }),
      });

      if (!openRouterResponse.ok) {
        throw new Error(`OpenRouter API error: ${openRouterResponse.status}`);
      }

      const completion = await openRouterResponse.json();
      const summary = completion.choices[0].message.content;

      if (!summary) {
        throw new Error('No summary generated by AI');
      }

      // Return the complete summary as JSON
      return NextResponse.json({ 
        success: true, 
        summary: summary,
        url: url 
      });

    } catch (aiError) {
      console.error('AI processing error:', aiError);
      return NextResponse.json(
        { error: `AI processing failed: ${aiError instanceof Error ? aiError.message : 'Unknown AI error'}` },
        { status: 500 }
      );
    }

  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown error occurred' },
      { status: 500 }
    );
  }
}
